import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import '@ant-design/v5-patch-for-react-19';
import 'antd/dist/reset.css';
import "./globals.css";
import { ReduxProvider } from "@/components/providers/ReduxProvider";
import { StompProvider } from "@/components/providers/StompProvider";
import AuthChecker from "@/components/auth/AuthChecker";
import { ThemeProvider } from "@/components/dashboard/theme-provider";
import AppThemeProvider from "@/components/providers/AppThemeProvider";
import { Toaster } from "@/components/dashboard/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next dashboard",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.className} antialiased bg-background text-foreground`}
      >
        {/* <ThemeProvider attribute="class" defaultTheme="system" enableSystem> */}
          <ReduxProvider>
            <AppThemeProvider>
              <StompProvider>
                <AuthChecker roles={[]} withAuth={false}>
                  {children}
                </AuthChecker>
              </StompProvider>
            </AppThemeProvider>
          </ReduxProvider>
          <Toaster richColors position={"top-center"}/>
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
